# =====================================================
# GENERAL SETTINGS
# =====================================================
[general]

# Enable/disable report generation (anomaly logs, etc.)
REPORT_MODE = oui

# Enable/disable saving plots
SAVE_PLOT = oui

# Feature vector name used by the model
VEC_FIELD = emb_dinov3


# =========================================================
# SYSTEM PATHS
# =========================================================
[paths]

# ==== Windows environment path ===========================
#
# Répertoire de sauvagarde Courbes & Fichiers d'erreur
WINDOWS = c:/Users/Pierre.FANCELLI/Documents/___Dev/__Back_Up

# Répertoire du Dataset 
DATA_WIN = C:\Users\Pierre.FANCELLI\Documents\___Dev\Aqua-IA\Data\coco_small
#DATA_WIN =


# ==== Linux environment path =============================
#
# Répertoire de sauvagarde Courbes & Fichiers d'erreur
LINUX = /media/DataLinux/Travail/_AKKA/___Akka_Reacher/Data

# Répertoire du Dataset 
DATA_LIN = /media/DataLinux/Travail/_AKKA/___Akka_Reacher/Data/coco_small_Work


# =========================================================
# DETECTION / EVALUATION
# Cas général     : 0.50  → 0.75
# Cas plus strict : 0.75 → 0.85
# Très strict     : 0.90 → 1.00
# =========================================================
[detection]

# Intersection over Union threshold for matching
IOU_THRESHOLD = 0.90


#--------- For Test - A suprimer ---------------------------------
#                       OK         Def
#   MIN_BBOX        = 1.0e-06   |  1.0e-04
#   MAX_BBOX        = 0.9998    |  0.9994 
#
#   MIN_BBOX_AREA   = 1.26e-10  |  1.26e-9
#   MAX_BBOX_AREA   = 0.9904    |  0.9902
#
#--------- For Test - A suprimer ---------------------------------

# =====================================================
# BOUNDING BOX CONSTRAINTS (YOLO normalized format)
#  from 0.0 to 1.0
# =====================================================
[bbox]

# Minimum / maximum bbox size relative to image
MIN_BBOX = 1.0e-06
MAX_BBOX = 0.9998 

# Minimum / maximum bbox area relative to image
MIN_BBOX_AREA = 1.26e-10
MAX_BBOX_AREA = 0.9904

# =====================================================
# ANOMALY THRESHOLDS (PERCENTILES)
# PERCENTILES WARNING : 70 → 90
# PERCENTILES ERROR : 90 → 99
#
# BBOX overflow WARNING : 5% → 20%
# BBOX overflow ERROR : 15% → 40%
#
# =====================================================
[percentiles]

# Percentile thresholds for anomaly detection
PERCENTILE_WARNING = 80
PERCENTILE_ERROR = 95

# Safety floors (avoid too low thresholds)
MIN_BBOX_OVERFLOW_WARNING = 15.0
MIN_BBOX_OVERFLOW_ERROR = 30.0


# =====================================================
# DATASET SETTINGS
# =====================================================
[dataset]

# Class imbalance thresholds (%)
RARE =0.30
DOMINANT = 2.0

# =====================================================
# QUALITY / SCORING THRESHOLDS
# 
# RATIO 
#   1 -  2 : Equilibré
#   2 - 10 : Acceptable
#  10 - 50 : Déséquilibré
#    > 100 : Trés déséquilibré 
#
# Entropie
#  0.90 - 1.00 : Trés équilibré
#  0.75 - 0.90 : Correct
#  0.50 - 0.75 : Déséquilibré
#      < 0.50  : Trés déséquilibré 
#
# Score
#  80 - 100 : Bon équilibre
#  60 - 80  : Acceptable
#  40 - 60  : Déséquilibré
#    < 40   : Trés déséquilibré  
#
# =====================================================
[scoring]

RATIO_OK = 10
RATIO_WARNING = 50

ENTROPY_OK = 0.80
ENTROPY_WARNING = 0.60

SCORE_OK = 80
SCORE_WARNING = 60
