# =====================================================
# GENERAL SETTINGS
# =====================================================
[general]

# Enable/disable saving plots
SAVE_PLOT = 0


# =========================================================
# SYSTEM PATHS
# =========================================================
[paths]

# ==== Windows environment path ===========================
#
# Répertoire de sauvagarde Courbes & Fichiers d'erreur
WINDOWS = c:/Users/Pierre.FANCELLI/Documents/___Dev/__Back_Up

# Répertoire du Dataset 
#DATA_WIN = C:\Users\Pierre.FANCELLI\Documents\___Dev\Aqua-IA\Data\coco128
DATA_WIN = C:\Users\Pierre.FANCELLI\Documents\___Dev\Aqua-IA\Data\coco_small
#DATA_WIN = C:\Users\Pierre.FANCELLI\Documents\___Dev\Aqua-IA\Data\coco_custom\petit
#DATA_WIN = C:\Users\Pierre.FANCELLI\Documents\___Dev\Aqua-IA\Data\coco_custom\moyen
#DATA_WIN = C:\Users\Pierre.FANCELLI\Documents\___Dev\Aqua-IA\Data\coco_custom\grand


# ==== Linux environment path =============================
#
# Répertoire de sauvagarde Courbes & Fichiers d'erreur
LINUX = /media/DataLinux/Travail/_AKKA/___Akka_Reacher/Data

# Répertoire du Dataset 
#DATA_LIN = /media/DataLinux/Travail/_AKKA/___Akka_Reacher/Data/coco_small
DATA_LIN = /media/DataLinux/Travail/_AKKA/___Akka_Reacher/Data/coco_custom/petit

# =========================================================
# DETECTION / EVALUATION
# Cas général     : 0.50  → 0.75
# Cas plus strict : 0.75 → 0.85
# Très strict     : 0.90 → 1.00
# =========================================================
[detection]

# Intersection over Union threshold for matching
IOU_THRESHOLD = 0.99

#--------- For Test - A suprimer ---------------------------------
#                       OK         Def
#   MIN_BBOX        = 1.0e-06   |  1.0e-04
#   MAX_BBOX        = 0.9998    |  0.9994 
#
#   MIN_BBOX_AREA   = 1.26e-10  |  1.26e-9
#   MAX_BBOX_AREA   = 0.9904    |  0.9902
#
#--------- For Test - A suprimer ---------------------------------

# =====================================================
# BOUNDING BOX CONSTRAINTS (YOLO normalized format)
#  from 0.0 to 1.0
# =====================================================
[bbox]

# Minimum / maximum bbox size relative to image
MIN_BBOX = 0.0
MAX_BBOX = 1.0
# Minimum / maximum bbox area relative to image
MIN_BBOX_AREA = 0.0
MAX_BBOX_AREA = 1.0
# =====================================================
# ANOMALY THRESHOLDS (PERCENTILES)
# PERCENTILES WARNING : 70 → 90
# PERCENTILES ERROR : 90 → 99
#
# BBOX overflow WARNING : 5% → 20%
# BBOX overflow ERROR : 15% → 40%
#
# =====================================================
[percentiles]

# Percentile thresholds for anomaly detection
PERCENTILE_WARNING = 90.0
PERCENTILE_ERROR = 99.0

# Safety floors (avoid too low thresholds)
MIN_BBOX_OVERFLOW_WARNING = 20.0
MIN_BBOX_OVERFLOW_ERROR =40.0


# =====================================================
# DATASET SETTINGS
# =====================================================
[dataset]

# Class imbalance thresholds (%)
RARE =0.30
DOMINANT = 2.0




# =====================================================
# Niveau de déséquilibre

#PROFILES = {
#    strict   : (0.05, 0.20),
#    normal   : (0.10, 0.30),
#    tolerant : (0.15, 0.40),
#
# =====================================================
[scoring]

PROFILES = strict   
